FROM golang:1.21.2-alpine3.18

RUN apk add bash git ruby rpm curl rsync tar binutils
RUN gem install --no-document fpm
ENV GOPATH=/tmp/go


RUN mkdir -p $GOPATH/src/github.com/github/gh-ost
WORKDIR $GOPATH/src/github.com/github/gh-ost
